# Generated by Django 5.1.3 on 2024-11-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('lecturer', 'Lecturer'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
